import { Toaster } from "react-hot-toast";
import "./globals.css";

import NextAuthProvider from "@/components/providers/NextAuthProvider";
import Layout from "@/components/layout/Layout";
import { yekan } from "@/utils/fonts";

export const metadata = {
  title: "پروژه املاک | پروژه فول استک next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        <NextAuthProvider>
          <Layout>{children}</Layout>
        </NextAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
