import { Toaster } from "react-hot-toast";
import "./globals.css";

import { yekan } from "@/utils/fonts";

export const metadata = {
  title: "پروژه املاک | پروژه فول استک next.js",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={yekan.className}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
